# Generated by Django 5.2.4 on 2025-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_event_asset_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='asset',
        ),
        migrations.AddField(
            model_name='event',
            name='thumb',
            field=models.ImageField(blank=True, default='events_thumbnail/default_thumb.jpg', null=True, upload_to='events_thumbnail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
