# Generated by Django 5.2.4 on 2025-07-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_remove_event_asset_event_thumb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='thumb',
        ),
    ]
