# Generated by Django 5.2.4 on 2025-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_event_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumb',
            field=models.ImageField(blank=True, default='events_thumbnail/default_thumb.jpg', null=True, upload_to='events_thumbnail'),
        ),
    ]
