# Generated by Django 5.2.4 on 2025-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_event_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumb',
            field=models.ImageField(blank=True, default='events_thumbnail/default_img.jpg', null=True, upload_to='events_thumbnail'),
        ),
    ]
